stages:
  - registry
  # - image

registry:
  image: golang:alpine
  stage: registry
  variables:
    GOARCH: arm
    GOOS: linux
    GOARM: 6
  script:
    - apk add --no-cache bash git build-base file make
    - make dist
  artifacts:
    paths:
      - bin/registry

image:
  image: docker:17.12
  services:
    - docker:17.12-dind
  stage: image
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - apk add --no-cache bash make
    - echo "http://dl-6.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
    - apk add --no-cache upx
    - make image
  dependencies:
    - registry
