stages:
  - registry
  - docker

registry:
  image: golang:alpine
  stage: registry
  variables:
    GOARCH: arm
    GOOS: linux
    GOARM: 6
  script:
    - apk add --no-cache bash git build-base file make
    - make dist
  artifacts:
    paths:
      - bin/registry

docker:
  image: docker:17.12
  services:
    - docker:17.12-dind
  stage: docker
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - apk add --no-cache bash make
    - echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
    - apk add --no-cache upx
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - make docker
  dependencies:
    - registry
