#!/bin/bash

set -eo pipefail

go get -d -v github.com/docker/distribution/cmd/registry
cd ${GOPATH}/src/github.com/docker/distribution
git checkout v2.6.2
sed -i -e 's/=\$(VERSION)"/=\$(VERSION) -s -w" -a/g' Makefile
make binaries
file bin/registry
cd -
cp ${GOPATH}/src/github.com/docker/distribution/bin/registry bin/registry